version: '2'

services:

  nba_visualizer:
    image: nba_visualizer:latest
    build: ""
    mem_limit: 100M
    restart: always
    ports:
     - "8081:80"

  postgres:
    restart: always
    image: postgres:9.6
    command: postgres -c logging_collector=on -c log_statement=all
    volumes:
      - ./dev-docker/SQL/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dev-docker/SQL/:/docker-entrypoint-initdb.d/
    ports:
      - "8432:5432"
    env_file:
      - dev-docker/db.env

  redis:
    image: 'redis:3.2.8'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    expose:
      - '6379'
    ports:
      - '6379:6379'
    restart: always
    env_file:
      - dev-docker/local_redis.env


#PGPASSWORD=password psql -h localhost -p 8432 -d db -U read_write_user -f insert_loans_data.psql